name: Validate changelog JSONs

on: [pull_request,push]

permissions:
  contents: read

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Changelog JSONs with Schema
        run: |
          ./scripts/validate-changelog-json.ps1
        shell: pwsh