name: Validate temp-docstubs folder

on: [pull_request, push]

permissions:
  contents: read

jobs:
  verify-temp-docstubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate temp-docstubs folder
        run: |
          ./validate-temp-docstubs.ps1
        shell: pwsh
